<?php

/**
 * @file
 * Slick slider for Drupal.
 */

/**
 * Implements hook_theme().
 */
function slick_theme($existing, $type, $theme, $path) {
  $base = array(
    'file' => 'slick.theme.inc',
    'path' => $path . '/templates',
  );
  return array(
    // Slick display.
    'slick' => $base + array(
      'render element' => 'elements',
      'template' => 'slick',
    ),
    // Individual slick item.
    'slick_item_wrapper' => $base + array(
      'render element' => 'element',
      'template' => 'slick-item-wrapper',
    ),
  );
}
